CREATE DATABASE IF NOT EXISTS satis_analiz CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE satis_analiz;

CREATE TABLE IF NOT EXISTS kategoriler (
    id INT AUTO_INCREMENT PRIMARY KEY,
    kategori_adi VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS bolgeler (
    id INT AUTO_INCREMENT PRIMARY KEY,
    bolge_adi VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS urunler (
    id INT AUTO_INCREMENT PRIMARY KEY,
    urun_adi VARCHAR(255) NOT NULL,
    kategori_id INT NOT NULL,
    fiyat DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (kategori_id) REFERENCES kategoriler(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS satislar (
    id INT AUTO_INCREMENT PRIMARY KEY,
    urun_id INT NOT NULL,
    bolge_id INT NOT NULL,
    adet INT NOT NULL,
    toplam_tutar DECIMAL(10, 2) NOT NULL,
    satis_tarihi TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (urun_id) REFERENCES urunler(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (bolge_id) REFERENCES bolgeler(id) ON DELETE RESTRICT ON UPDATE CASCADE
);
